### ISSUE TITLE
URL using bad/illegal format or missing URL everytime

### ISSUE THREAD

**Issue by mrdev023** [getbrevo/brevo-ruby#3]
Basic request not work.

```
Ethon::Easy.new(url: "google.com").perform
ETHON: Libcurl initialized
ETHON: performed EASY effective_url=www.example.com response_code=0 return_code=url_malformat total_time=0.0
=> :url_malformat
```

**Comment by mrdev023** [comment]
https://github.com/typhoeus/ethon/issues/238

**Comment by mrdev023** [comment]
Finally, in repo, current MR and issue not receive reply so think is not maintained actively

**Comment by NagendraSIB** [comment]
Hi @mrdev023 
Sorry for the delay, I missed the notification.

Can you please share the ruby code & on which endpoint you are trying ?

**Comment by mrdev023** [comment]
> Hi @mrdev023 Sorry for the delay, I missed the notification.
> 
> Can you please share the ruby code & on which endpoint you are trying ?

https://github.com/getbrevo/brevo-ruby?tab=readme-ov-file#getting-started 

And i have this bug with newer version of libcurl.

In my fedora 39, it works well (libcurl 8.2). https://fedora.pkgs.org/39/fedora-x86_64/libcurl-8.2.1-3.fc39.x86_64.rpm.html
In my NixOS, it doesn't work (libcurl 8.7.1) https://search.nixos.org/packages?channel=unstable&show=curl&from=0&size=50&sort=relevance&type=packages&query=curl

**Comment by mrdev023** [comment]
I no longer use the official gem but this https://github.com/unovafr/brevo-openapi one which I regenerated from your documentation

i use https://github.com/unovafr/brevo-openapi/blob/main/flake.nix#L14 faraday library instead of typhoeus

**Comment by mrdev023** [comment]
*STATUS* : Not reproduced

Code
```ruby
require 'brevo'
Brevo::AccountApi.new.get_account
```

If return Unauthorized (Brevo::ApiError) so it's ok
otherwise return URL using bad/illegal format or missing URL

Fedora (8.2.1) =>  OK
Arch (8.7.1) => OK

**Comment by mrdev023** [comment]
I think finally it's a bug libcurl side or distroside all my previous test work well now. I close issue after test your gem in my project with full environment and if is work well also.

**Comment by mrdev023** [comment]
It work on alpine 3.18 in our side i close this issue
